<?php
    $_product = $this->getProduct();
?>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery(".btn-cart").click(
            function(){
                validationResult = productAddToCartForm.validator.validate();

                if (validationResult) {
                    jQuery("<?php echo $this->getDestinationBlock(); ?>").flyTo(<?php echo json_encode($this->getConfig()); ?>);
                }
            }
        )
    });
</script>
